1: London W1 Tottenham Crt Rd
2: London W1 Rathbone Place
10: Harrow
11: Birmingham
19: Watford
22: Hounslow
24: Bromley
27: Kingston
29: Leeds
31: Southampton
37: Solihull
38: Northampton
39: Liverpool
42: Wolverhampton
43: Bristol
44: Nottingham
46: Brighton
47: Leicester Gallowtree Gate
48: Sheffield
49: Bradford
50: Stoke
51: Plymouth
52: Glasgow Union St
54: Edinburgh
56: Hemel Hempstead
57: Belfast
58: Ballymena
59: Lisburn
60: Newry
61: Hull
62: Tunbridge Wells
63: Swindon
65: Doncaster
66: Gloucester
68: Coventry - Hertford St
69: Luton
71: Merry Hill
72: Derby
74: Wakefield
75: Manchester Arndale
76: Liverpool Lord St
77: Bedford
78: Ipswich
79: Derby Phone Exchange
80: Wood Green
81: Worcester
82: Basingstoke
83: Preston
84: Sutton
85: Huddersfield
86: Darlington
87: Croydon - George St
89: Bolton
90: Rugby Phone Exchange
91: Wigan
92: Coleraine
93: Leicester Phone Exchange
94: Barking
95: Wrexham
96: Stevenage
97: Enniskillen
98: Middlesbrough
99: Romford
100: St Albans
101: Maidstone
103: Cheltenham
104: Exeter
105: Uxbridge
106: Lincoln
107: Enfield
108: Londonderry
109: Andover
110: Walsall
111: Redditch
112: Tooting
113: Warrington
114: Portsmouth
115: Chatham
116: Dewsbury
117: Slough
118: Sunderland
119: Crawley
120: Stratford
121: Woking
122: Leamington Spa
123: Ilford
124: Stockport
125: High Wycombe
126: Camden
128: Streatham
129: Southend
130: Bridlington
131: South Shields
133: Staines
134: Scunthorpe
135: Halifax
136: Yeovil
137: Aylesbury
138: Bournemouth
139: Elephant And Castle
140: Barnsley
141: Ashford
142: Bexleyheath
143: Chesterfield
144: Nuneaton
145: Walthamstow
147: Shepherds Bush
148: Harlow
149: Grimsby
150: Blackpool
151: Oldham
152: Bury
153: Reading
155: Basildon
156: Mansfield
157: Brentwood
158: Edmonton
159: Washington
160: Taunton
161: Birkenhead
163: Great Yarmouth
165: Southport
166: Milton Keynes
167: Maidenhead
168: Norwich
169: Hereford
170: Loughborough
171: Fulham
180: Hartlepool
181: Wimbledon
182: Kilburn
183: Canterbury
184: West Bromwich
185: Worthing
186: Scarborough
187: St Helens
188: Gravesend
189: Dalston - Hackney
190: Kings Lynn
191: Poole
192: Banbury
193: Woolwich
194: Torquay
195: Chippenham
196: Colchester
197: Aberdeen
198: Dundee
199: Ashton Under Lyne
200: Camberley
201: Kettering
202: Kidderminster
203: Bootle
204: Tamworth
205: Barnet
206: Salford
207: Telford
208: Guildford
209: Inverness
210: Castleford
211: Lewisham
212: Sutton Coldfield
213: Stourbridge
214: Lowestoft
215: Sittingbourne
216: Newcastle Grainger St
217: Stirling
219: Bayswater
220: Dartford
221: Cramlington
222: Swansea
225: Gateshead Metro Centre
226: Redhill
227: Harrogate
228: Burnley
229: Peckham
230: Macclesfield
231: Burton On Trent
232: Belfast Ann Street
233: Kings Heath
234: Cambridge
235: Farnborough
236: Bangor
237: Dudley
238: Erdington
239: Gateshead Trinity Square
240: Barnstaple
241: Boscombe
242: Bridgwater
243: Brixton
244: York
245: Northfield
248: Bournemouth - Castlepoint
249: Wakefield - The Springs
250: Cardiff - St Davids
251: Wythenshawe
252: Skelmersdale
253: Glasgow Sauchiehall
254: Barrow-In-Furness
255: Dagenham
256: Grantham
257: Newport
258: Grays
259: Dunfermline
261: Perry Barr
262: Chelmsford
263: Rochdale
264: Winchester
265: Durham
266: East Kilbride
267: Beeston
268: Crewe
269: Accrington
270: Aldershot
271: Falkirk
272: Motherwell
274: Runcorn
275: Folkestone
276: Keighley
277: Altrincham
278: Fareham
279: Cwmbran
280: Peterborough
281: Eastbourne
282: Stockton
284: Shrewsbury Castle Street
285: Newbury
286: Acocks Green
287: Widnes
289: Bilston
291: Melton Mowbray
292: Cumbernauld
294: Peterlee
295: Ayr
297: Newtownabbey
298: Wembley
299: Rotherham
300: Carlisle
301: Chelmsley Wood
302: Worksop
303: Newcastle under Lyme
305: Dover
306: Stafford
307: Eltham
308: Lancaster
309: Blackburn
310: Corby
311: Weymouth
315: Livingston
316: Bognor Regis
317: Tonbridge
321: Pontypridd
322: Salisbury
323: Ramsgate
324: Braintree
325: Gillingham
326: East Ham
327: Eastleigh
328: Wellingborough
333: Crystal Peaks
335: Orpington
336: Evesham
337: Lichfield
338: Greenock
340: Waltham Cross
341: Hinckley
342: Chorley
3001: Halesowen
3002: Thetford
3003: Truro
3004: Port Talbot
3005: Clydebank
3006: Northampton - Weston Favell
3007: Barry
3008: Leeds Crossgates
3009: Bishops Stortford
3010: Newtownards
3011: Kirkcaldy
3012: Perth
3013: Hull Northpoint
3015: Skegness
3016: Newmarket
3017: Edinburgh Cameron Toll
3018: Stroud
3019: St Austell
3020: Windsor
3021: Hatfield
3022: Chester
3023: Ellesmere Port
3024: Hull Whitefriargate
3025: Stratford upon Avon
3027: Ashington
3028: Belle Vale
3029: Retford
3030: Bath
3032: Hammersmith
3033: Bishop Auckland
3034: Clapham Junction
3035: Holloway
3037: Craigavon
3038: Wolverhampton Wulfrun
3039: Newport IsleOfWight
3040: Kendal
3041: SuttonInAshfield
3043: Bletchley
3044: WestonSuperMare
3045: Carmarthen
3046: Burgess Hill
3047: Chichester
3048: Merthyr Tydfil
3050: Oxford Cowley
3052: Arnold
3054: Leigh
3055: Epsom
3056: Gosport
3057: Yate
3058: Havant
3059: Clacton on Sea
3060: Douglas
3061: Margate
3062: Long Eaton
3063: Morden
3064: Northallerton
3065: North Shields
3066: Welwyn Garden City
3068: Irvine
3069: Paisley
3070: Penzance
3071: Rhyl
3072: East Grinstead
3073: Glasgow Forge
3074: Hove
3075: Palmers Green
3076: Bangor Wales
3077: Nottingham Victoria
3078: Southampton  Shirley
3079: Borehamwood
3080: Hastings
3081: Coalville
3082: Letchworth
3083: Middleton
3084: Glenrothes
3086: Felixstowe
3087: Horsham
3088: Hertford
3090: Exmouth
3091: Street
3093: Buxton
3096: Boston Bargate
3099: Kennedy Centre
3100: Bridgend
3109: Kilmarnock
3110: Dunstable
3111: Edgware
3112: Cookstown
3115: Edinburgh Leith
3130: Bromsgrove
3133: Coventry Cannon Park
3139: Portsmouth North End
3142: Ilkeston
3147: Leeds White Rose
3150: Newcastle upon Tyne
3153: Ruislip
3155: Feltham
3156: Redcar
3165: Beaumont Leys Leicester
3166: Huntingdon
3167: Bearwood
3170: Kingswood
3173: Deptford
3174: Islington
3176: Nantwich
3177: Trowbridge
3178: Morley
3179: Wandsworth
3181: Whitechapel
3182: Lakeside
3184: Denton
3186: Catterick
3188: Beverley
3190: Bulwell
3191: Whitby
3192: Northwich
3193: Bedminster
3198: North Finchley
3199: Bracknell
